version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
    ports:
      - '5433:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-init_auth.db/init.sql

