server:
  port: 8081

spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: auth
    password: auth
  flyway:
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/auth
    username: auth
    password: auth



jwt:
  secret-key: awmvskjviwlkdjsvnwjwjdkajmenwdj@=
