### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8081/v1/auth/reissue
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MTU2MDg1OTAsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MTYwNDA1OTAsImlhdCI6MTcxNTYwODU5MH0.MwcA2pAjk5l1M7-5mkYtwPX7ZlB4a6sCSqPsROZ9cwo-7hYKFK3fdcolkm9EoUfTZQWf8KdNTUm31-FRwoNIyolmk7bAhfB2N64DRrgYlX7RSIvDqDJvWpru4y82q41_vFCJE3MYfeAaj8duRdYx-BBDtYGLBJJAqe9ayJ5gIrYf-OyM2PGzvVRV2hr41vFNVYfaP3tY-4eJ93Cksz1M4bLBaUL5nGtYPrZvKDolxbHOD1H9ygDWpNyZVQmVpudz0ArjNumLi7mn_HXrbfDGZw8768L8E3lp4GE9QbIZHDF77JjkbcO_BBJnqJMMBg9jD4ixHK4TlRslXFabSap_Fw
