name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    
    - name: Build JAR
      run: ./gradlew build -x test

    - name: Determine ECR Repository
      id: ecr_repo
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print $2}' | tr '[:upper:]' '[:lower:]')
        
        echo "repo=${REPO_NAME}" >> $GITHUB_OUTPUT

        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          echo "environment=stag" >> $GITHUB_OUTPUT
        else
          echo "::error::Unsupported branch: ${{ github.event_name }} on ${{ github.ref }}"
          exit 1
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker Build and Push
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ steps.ecr_repo.outputs.repo }}_${{ steps.ecr_repo.outputs.environment }}:${{ github.sha }} .
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ steps.ecr_repo.outputs.repo }}_${{ steps.ecr_repo.outputs.environment }}:${{ github.sha }}

    - name: Checkout Private Repository
      uses: actions/checkout@v4
      with:
        repository: NTF-marketplace/devops
        fetch-depth: 0
        ref: develop
        token: ${{ secrets.PAT }}

    - name: Replace image tag in helm values (LOCAL)
      uses: mikefarah/yq@master
      env:
        IMAGE_TAG: ${{ github.sha }}
      with:
        cmd: yq eval -i '.image.tag = env(IMAGE_TAG)' 'chart/${{ steps.ecr_repo.outputs.repo }}_${{ steps.ecr_repo.outputs.environment }}/values.yaml'

    - name: Commit helm chart changes
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd chart/${{ steps.ecr_repo.outputs.repo }}_${{ steps.ecr_repo.outputs.environment }}
        git config --global user.email "hun5879@naver.com"
        git config --global user.name "dongdorrong"

        git add values.yaml
        git commit --message "ci: update ${{ steps.ecr_repo.outputs.repo }}_${{ steps.ecr_repo.outputs.environment }} image tag to $IMAGE_TAG"

    - name: Push commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        repository: NTF-marketplace/devops